// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GroupMember struct {
	UserID   uuid.UUID `json:"user_id"`
	GroupID  uuid.UUID `json:"group_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type JobGroup struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	InvitationCode string    `json:"invitation_code"`
	OwnerID        uuid.UUID `json:"owner_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ShiftTrade struct {
	ID                uuid.UUID     `json:"id"`
	GroupID           uuid.UUID     `json:"group_id"`
	RequesterID       uuid.UUID     `json:"requester_id"`
	AcceptorID        uuid.NullUUID `json:"acceptor_id"`
	ShiftStartAt      time.Time     `json:"shift_start_at"`
	ShiftEndAt        time.Time     `json:"shift_end_at"`
	BountyDescription string        `json:"bounty_description"`
	Status            string        `json:"status"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	IsPaid            bool          `json:"is_paid"`
	Details           string        `json:"details"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	LineUserID      string         `json:"line_user_id"`
	DisplayName     string         `json:"display_name"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
