// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// シフト交代リクエストの応募
	AcceptShiftTrade(ctx context.Context, arg AcceptShiftTradeParams) (ShiftTrade, error)
	// 退会ユーザーが作成した「募集中(OPEN)」の募集を全てCLOSEDにする
	CloseOpenShiftTradesByRequester(ctx context.Context, requesterID uuid.UUID) (int64, error)
	// グループ参加
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error)
	// グループ作成
	CreateJobGroup(ctx context.Context, arg CreateJobGroupParams) (JobGroup, error)
	// シフト交代リクエスト作成
	CreateShiftTrade(ctx context.Context, arg CreateShiftTradeParams) (ShiftTrade, error)
	// internal/database/query.sql
	// ユーザー作成
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// シフト交代リクエストの削除
	DeleteShiftTrade(ctx context.Context, arg DeleteShiftTradeParams) (int64, error)
	// グループ所属チェック
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	// グループメンバー全員のLINE IDを取得 (通知用)
	GetGroupMemberLineIDs(ctx context.Context, groupID uuid.UUID) ([]string, error)
	// グループ名取得
	GetGroupName(ctx context.Context, id uuid.UUID) (string, error)
	// 招待コードでグループ検索
	GetJobGroupByCode(ctx context.Context, invitationCode string) (JobGroup, error)
	// IDでグループ情報を取得 (画面表示用)
	GetJobGroupByID(ctx context.Context, id uuid.UUID) (JobGroup, error)
	// シフト交代リクエストを id で取得
	GetTradeByID(ctx context.Context, id uuid.UUID) (ShiftTrade, error)
	// IDでユーザー情報を取得 (画面表示用)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// LINE IDでユーザー取得
	GetUserByLineID(ctx context.Context, lineUserID string) (User, error)
	// そのグループの「募集中(OPEN)」のシフト一覧を取得
	ListOpenShiftTrades(ctx context.Context, groupID uuid.UUID) ([]ListOpenShiftTradesRow, error)
	// 指定された時間範囲にある未成立シフトを取得 (リマインド通知用)
	ListUnfilledShiftsInWindow(ctx context.Context, arg ListUnfilledShiftsInWindowParams) ([]ListUnfilledShiftsInWindowRow, error)
	// ユーザーが所属しているグループ一覧を取得
	ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error)
	// 自分の関わったトレード履歴を取得 (作成したもの OR 引き受けたもの)
	ListUserTrades(ctx context.Context, requesterID uuid.UUID) ([]ShiftTrade, error)
	// 謝礼を支払い済みにする
	MarkTradeAsPaid(ctx context.Context, arg MarkTradeAsPaidParams) (ShiftTrade, error)
	// シフト交代リクエストの詳細を編集
	UpdateTradeDetails(ctx context.Context, arg UpdateTradeDetailsParams) (ShiftTrade, error)
	// id指定でユーザー論理削除
	WithdrawUser(ctx context.Context, arg WithdrawUserParams) error
}

var _ Querier = (*Queries)(nil)
