// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acceptShiftTrade = `-- name: AcceptShiftTrade :one
UPDATE shift_trades
SET
    acceptor_id = $1,
    status = 'FILLED',
    updated_at = NOW()
WHERE
    id = $2
    AND status = 'OPEN'
    AND requester_id != $1
    AND EXISTS (
      SELECT 1
      FROM group_members gm
      WHERE gm.user_id = $1 AND gm.group_id = $3
    )
RETURNING id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details
`

type AcceptShiftTradeParams struct {
	AcceptorID uuid.NullUUID `json:"acceptor_id"`
	ID         uuid.UUID     `json:"id"`
	GroupID    uuid.UUID     `json:"group_id"`
}

// シフト交代リクエストの応募
func (q *Queries) AcceptShiftTrade(ctx context.Context, arg AcceptShiftTradeParams) (ShiftTrade, error) {
	row := q.db.QueryRowContext(ctx, acceptShiftTrade, arg.AcceptorID, arg.ID, arg.GroupID)
	var i ShiftTrade
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequesterID,
		&i.AcceptorID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.BountyDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPaid,
		&i.Details,
	)
	return i, err
}

const closeOpenShiftTradesByRequester = `-- name: CloseOpenShiftTradesByRequester :execrows
UPDATE shift_trades
SET status = 'CLOSED',
    updated_at = NOW()
WHERE requester_id = $1
  AND status = 'OPEN'
`

// 退会ユーザーが作成した「募集中(OPEN)」の募集を全てCLOSEDにする
func (q *Queries) CloseOpenShiftTradesByRequester(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenShiftTradesByRequester, requesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (user_id, group_id, role)
VALUES ($1, $2, $3)
    RETURNING user_id, group_id, role, joined_at
`

type CreateGroupMemberParams struct {
	UserID  uuid.UUID `json:"user_id"`
	GroupID uuid.UUID `json:"group_id"`
	Role    string    `json:"role"`
}

// グループ参加
func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, createGroupMember, arg.UserID, arg.GroupID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createJobGroup = `-- name: CreateJobGroup :one
INSERT INTO job_groups (name, invitation_code, owner_id)
VALUES ($1, $2, $3)
    RETURNING id, name, invitation_code, owner_id, created_at, updated_at
`

type CreateJobGroupParams struct {
	Name           string    `json:"name"`
	InvitationCode string    `json:"invitation_code"`
	OwnerID        uuid.UUID `json:"owner_id"`
}

// グループ作成
func (q *Queries) CreateJobGroup(ctx context.Context, arg CreateJobGroupParams) (JobGroup, error) {
	row := q.db.QueryRowContext(ctx, createJobGroup, arg.Name, arg.InvitationCode, arg.OwnerID)
	var i JobGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvitationCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShiftTrade = `-- name: CreateShiftTrade :one
INSERT INTO shift_trades (
    group_id, requester_id, shift_start_at, shift_end_at, bounty_description
) VALUES (
             $1, $2, $3, $4, $5
         )
    RETURNING id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details
`

type CreateShiftTradeParams struct {
	GroupID           uuid.UUID `json:"group_id"`
	RequesterID       uuid.UUID `json:"requester_id"`
	ShiftStartAt      time.Time `json:"shift_start_at"`
	ShiftEndAt        time.Time `json:"shift_end_at"`
	BountyDescription string    `json:"bounty_description"`
}

// シフト交代リクエスト作成
func (q *Queries) CreateShiftTrade(ctx context.Context, arg CreateShiftTradeParams) (ShiftTrade, error) {
	row := q.db.QueryRowContext(ctx, createShiftTrade,
		arg.GroupID,
		arg.RequesterID,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.BountyDescription,
	)
	var i ShiftTrade
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequesterID,
		&i.AcceptorID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.BountyDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPaid,
		&i.Details,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (line_user_id, display_name, profile_image_url)
VALUES ($1, $2, $3)
    RETURNING id, line_user_id, display_name, profile_image_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	LineUserID      string         `json:"line_user_id"`
	DisplayName     string         `json:"display_name"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
}

// internal/database/query.sql
// ユーザー作成
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.LineUserID, arg.DisplayName, arg.ProfileImageUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LineUserID,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteShiftTrade = `-- name: DeleteShiftTrade :execrows
DELETE FROM shift_trades
WHERE id = $1 AND requester_id = $2 AND status = 'OPEN'
`

type DeleteShiftTradeParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

// シフト交代リクエストの削除
func (q *Queries) DeleteShiftTrade(ctx context.Context, arg DeleteShiftTradeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteShiftTrade, arg.ID, arg.RequesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT user_id, group_id, role, joined_at FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// グループ所属チェック
func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMemberLineIDs = `-- name: GetGroupMemberLineIDs :many
SELECT u.line_user_id
FROM group_members gm
         JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
  AND u.line_user_id IS NOT NULL
  AND u.line_user_id != ''
`

// グループメンバー全員のLINE IDを取得 (通知用)
func (q *Queries) GetGroupMemberLineIDs(ctx context.Context, groupID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMemberLineIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var line_user_id string
		if err := rows.Scan(&line_user_id); err != nil {
			return nil, err
		}
		items = append(items, line_user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupName = `-- name: GetGroupName :one
SELECT name FROM job_groups
WHERE id = $1
`

// グループ名取得
func (q *Queries) GetGroupName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getJobGroupByCode = `-- name: GetJobGroupByCode :one
SELECT id, name, invitation_code, owner_id, created_at, updated_at FROM job_groups
WHERE invitation_code = $1 LIMIT 1
`

// 招待コードでグループ検索
func (q *Queries) GetJobGroupByCode(ctx context.Context, invitationCode string) (JobGroup, error) {
	row := q.db.QueryRowContext(ctx, getJobGroupByCode, invitationCode)
	var i JobGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvitationCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobGroupByID = `-- name: GetJobGroupByID :one
SELECT id, name, invitation_code, owner_id, created_at, updated_at FROM job_groups WHERE id = $1
`

// IDでグループ情報を取得 (画面表示用)
func (q *Queries) GetJobGroupByID(ctx context.Context, id uuid.UUID) (JobGroup, error) {
	row := q.db.QueryRowContext(ctx, getJobGroupByID, id)
	var i JobGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvitationCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTradeByID = `-- name: GetTradeByID :one
SELECT id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details FROM shift_trades WHERE id = $1
`

// シフト交代リクエストを id で取得
func (q *Queries) GetTradeByID(ctx context.Context, id uuid.UUID) (ShiftTrade, error) {
	row := q.db.QueryRowContext(ctx, getTradeByID, id)
	var i ShiftTrade
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequesterID,
		&i.AcceptorID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.BountyDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPaid,
		&i.Details,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, line_user_id, display_name, profile_image_url, created_at, updated_at, deleted_at FROM users WHERE id = $1
`

// IDでユーザー情報を取得 (画面表示用)
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LineUserID,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByLineID = `-- name: GetUserByLineID :one
SELECT id, line_user_id, display_name, profile_image_url, created_at, updated_at, deleted_at FROM users
WHERE line_user_id = $1
  AND deleted_at IS NULL
    LIMIT 1
`

// LINE IDでユーザー取得
func (q *Queries) GetUserByLineID(ctx context.Context, lineUserID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLineID, lineUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LineUserID,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOpenShiftTrades = `-- name: ListOpenShiftTrades :many
SELECT
    t.id, t.shift_start_at, t.shift_end_at, t.bounty_description, t.created_at,
    u.display_name as requester_name,
    u.profile_image_url as requester_image
FROM shift_trades t
         JOIN users u ON t.requester_id = u.id
WHERE t.group_id = $1 AND t.status = 'OPEN'
  AND t.shift_start_at > NOW()
ORDER BY t.shift_start_at ASC
`

type ListOpenShiftTradesRow struct {
	ID                uuid.UUID      `json:"id"`
	ShiftStartAt      time.Time      `json:"shift_start_at"`
	ShiftEndAt        time.Time      `json:"shift_end_at"`
	BountyDescription string         `json:"bounty_description"`
	CreatedAt         time.Time      `json:"created_at"`
	RequesterName     string         `json:"requester_name"`
	RequesterImage    sql.NullString `json:"requester_image"`
}

// そのグループの「募集中(OPEN)」のシフト一覧を取得
func (q *Queries) ListOpenShiftTrades(ctx context.Context, groupID uuid.UUID) ([]ListOpenShiftTradesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenShiftTrades, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenShiftTradesRow
	for rows.Next() {
		var i ListOpenShiftTradesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShiftStartAt,
			&i.ShiftEndAt,
			&i.BountyDescription,
			&i.CreatedAt,
			&i.RequesterName,
			&i.RequesterImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfilledShiftsInWindow = `-- name: ListUnfilledShiftsInWindow :many
SELECT t.id, t.group_id, t.requester_id, t.acceptor_id, t.shift_start_at, t.shift_end_at, t.bounty_description, t.status, t.created_at, t.updated_at, t.is_paid, t.details, u.line_user_id
FROM shift_trades t
         JOIN users u ON t.requester_id = u.id
WHERE t.status = 'OPEN'
  AND t.shift_start_at >= $1
  AND t.shift_start_at < $2
`

type ListUnfilledShiftsInWindowParams struct {
	ShiftStartAt   time.Time `json:"shift_start_at"`
	ShiftStartAt_2 time.Time `json:"shift_start_at_2"`
}

type ListUnfilledShiftsInWindowRow struct {
	ID                uuid.UUID     `json:"id"`
	GroupID           uuid.UUID     `json:"group_id"`
	RequesterID       uuid.UUID     `json:"requester_id"`
	AcceptorID        uuid.NullUUID `json:"acceptor_id"`
	ShiftStartAt      time.Time     `json:"shift_start_at"`
	ShiftEndAt        time.Time     `json:"shift_end_at"`
	BountyDescription string        `json:"bounty_description"`
	Status            string        `json:"status"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	IsPaid            bool          `json:"is_paid"`
	Details           string        `json:"details"`
	LineUserID        string        `json:"line_user_id"`
}

// 指定された時間範囲にある未成立シフトを取得 (リマインド通知用)
func (q *Queries) ListUnfilledShiftsInWindow(ctx context.Context, arg ListUnfilledShiftsInWindowParams) ([]ListUnfilledShiftsInWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnfilledShiftsInWindow, arg.ShiftStartAt, arg.ShiftStartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnfilledShiftsInWindowRow
	for rows.Next() {
		var i ListUnfilledShiftsInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.RequesterID,
			&i.AcceptorID,
			&i.ShiftStartAt,
			&i.ShiftEndAt,
			&i.BountyDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPaid,
			&i.Details,
			&i.LineUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.invitation_code, gm.role
FROM job_groups g
         JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type ListUserGroupsRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	InvitationCode string    `json:"invitation_code"`
	Role           string    `json:"role"`
}

// ユーザーが所属しているグループ一覧を取得
func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InvitationCode,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTrades = `-- name: ListUserTrades :many
SELECT id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details FROM shift_trades
WHERE (requester_id = $1 OR acceptor_id = $1)
ORDER BY shift_start_at DESC
`

// 自分の関わったトレード履歴を取得 (作成したもの OR 引き受けたもの)
func (q *Queries) ListUserTrades(ctx context.Context, requesterID uuid.UUID) ([]ShiftTrade, error) {
	rows, err := q.db.QueryContext(ctx, listUserTrades, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftTrade
	for rows.Next() {
		var i ShiftTrade
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.RequesterID,
			&i.AcceptorID,
			&i.ShiftStartAt,
			&i.ShiftEndAt,
			&i.BountyDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPaid,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTradeAsPaid = `-- name: MarkTradeAsPaid :one
UPDATE shift_trades
SET is_paid = true, updated_at = NOW()
WHERE id = $1 AND requester_id = $2
    RETURNING id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details
`

type MarkTradeAsPaidParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

// 謝礼を支払い済みにする
func (q *Queries) MarkTradeAsPaid(ctx context.Context, arg MarkTradeAsPaidParams) (ShiftTrade, error) {
	row := q.db.QueryRowContext(ctx, markTradeAsPaid, arg.ID, arg.RequesterID)
	var i ShiftTrade
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequesterID,
		&i.AcceptorID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.BountyDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPaid,
		&i.Details,
	)
	return i, err
}

const updateTradeDetails = `-- name: UpdateTradeDetails :one
UPDATE shift_trades
SET details = $3,
    updated_at = NOW()
WHERE id = $1 AND requester_id = $2
    RETURNING id, group_id, requester_id, acceptor_id, shift_start_at, shift_end_at, bounty_description, status, created_at, updated_at, is_paid, details
`

type UpdateTradeDetailsParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
	Details     string    `json:"details"`
}

// シフト交代リクエストの詳細を編集
func (q *Queries) UpdateTradeDetails(ctx context.Context, arg UpdateTradeDetailsParams) (ShiftTrade, error) {
	row := q.db.QueryRowContext(ctx, updateTradeDetails, arg.ID, arg.RequesterID, arg.Details)
	var i ShiftTrade
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequesterID,
		&i.AcceptorID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.BountyDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPaid,
		&i.Details,
	)
	return i, err
}

const withdrawUser = `-- name: WithdrawUser :exec
UPDATE users
SET line_user_id = $2,
    display_name = $3,
    deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type WithdrawUserParams struct {
	ID          uuid.UUID `json:"id"`
	LineUserID  string    `json:"line_user_id"`
	DisplayName string    `json:"display_name"`
}

// id指定でユーザー論理削除
func (q *Queries) WithdrawUser(ctx context.Context, arg WithdrawUserParams) error {
	_, err := q.db.ExecContext(ctx, withdrawUser, arg.ID, arg.LineUserID, arg.DisplayName)
	return err
}
